--- 
title: "Redes de Computadoras"
author: "José Alberto Incera Diéguez"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
csl: ieee.csl
link-citations: yes
github-repo: IsaacAPM/bookdown_redes
description: "Este libro contiene el material de apoyo para el curso de Redes de Computadoras que se imparte en el Instituto Tecnológico Autónomo de México"
---


# Prólogo {-}

Este documento contiene el material de apoyo para los cursos de Redes de Computadoras que se imparten en el Instituto Tecnológico Autónomo de México.

La estructuración del material sigue un modelo ascendente, de la capa física a la capa de aplicación, común en libros de texto clásicos de redes de computadoras.   

El material ha sido integrado a lo largo de varios años de impartir estas materias en los niveles de licenciatura, maestría y diplomado. En él han participado varios profesores, entre los que cabe destacar: Dr. Uciel Fragoso, Dr. Federico Kuhlmann, Dr. José A. Incera, Dr. Marcelo Mejía y M.T. Ramón Ríos.

Este mismo libro ha sido escrito en [R-Markdown](http://rmarkdown.rstudio.com) empleando el paquete [`bookdown`](https://bookdown.org/yihui/bookdown/)  y está disponible en el repositorio Github: [IsaacAPM/bookdown_redes](https://github.com/IsaacAPM/bookdown_redes). 


```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
# funciones auxiliares
inline <- function(x = "") paste0("`` `r ", x, "` ``")
inline2 <- function(x = "") paste0("`r ", x, "`")
```
